---
title: "Projet Text mining : Sentiment Analysis"
author:
- name: Salim Igué
  affiliation: Université François Rabelais de Tours
- name: Kévin Marnay
  affiliation: Université François Rabelais de Tours
date: "`r format(Sys.time(), '%d %B %Y')`"
tags: [nothing, nothingness]
abstract: |
  Abstract

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Markdown



```{r warning=FALSE}

cheminN <-"Datasets/reviews/N/"

val1 <- "N"
datasetNegative <- data.frame()
test<-data.frame()



#Extraction

  dataset1 <- data.frame()
  
  
  for(fich in dir(path=cheminN, pattern="*.txt$", recursive=TRUE)){
    res =  read.delim(paste0(cheminN,fich), header = FALSE, dec = ".")
    res$V1<-as.character(res$V1)
    tmp<-paste(res$V1,collapse = " ")
    
    test<-rbind(test,tmp)
    test<- cbind(test,val1)
    names(test) <- c("text","class")
    dataset1 <- rbind.data.frame(dataset1,test)
    test<-data.frame()
  }
  datasetNegative <- rbind(datasetNegative,dataset1)
  dataset1 <- data.frame()
  

  datasetNegative$text<-as.character(datasetNegative$text)
 rm(res,dataset1,test,cheminN,fich,tmp,val1)
```
  
  



Ainsi pour afficher le contenu de notre dataframe on a: 

```{r}


```


